### ISSUE TITLE
"Defaults    requiretty" didn't work with Vagrant

### ISSUE THREAD

**Issue by SydOps** [saz/puppet-sudo#101]
The option `Defaults    requiretty` is enabled  in both `files/sudoers.rhel5`  and `files/sudoers.rhel6` as default. But when apply this puppet module in Vagrant CentOS 6.5 instance, always get the error:

    sudo: sorry, you must have a tty to run sudo

the fix is here: [comment it](http://stackoverflow.com/questions/26945985/which-centos-image-can-i-use-on-aws-with-vagrant). 

This is the explanation: 

http://unix.stackexchange.com/questions/122616/why-do-i-need-a-tty-to-run-sudo-if-i-can-sudo-without-a-password
https://bugzilla.redhat.com/show_bug.cgi?id=1020147

Any suggestion that I can still `librarian-puppet` this module, but get that line commented?

Or could you please comment this line in your code directly?

**Comment by SydOps** [comment]
a closed issue has discussed it befoer 
https://github.com/saz/puppet-sudo/issues/76

**Comment by saz** [comment]
I think, there should be some information in the docs, how to solve this problem, as it is easily solvable without _any_ change in this module.

Maybe you'll got some time to create a pull request?

**Comment by SydOps** [comment]
I have raised the pull request.

**Comment by saz** [comment]
I'm good with the change, but this needs to be addressed in a better way:

1. remove the line, including any comment. Do not comment them out (especially since the comment is wrong)
2. remove the lines from all rhel files (5, 6 and 7)

I think this should solve the problem completely.

**Comment by SydOps** [comment]
My latest pull request has been passed the validation. Waiting for the merge.

**Comment by SydOps** [comment]
@saz , any updates for my pull request?

**Comment by SydOps** [comment]
For anyone who stuck with this issue, and still waiting the pull request to be merged. Run below command in your Vagrantfile, it will bypass this issue. 

    config.vm.provision "shell", :inline => "echo 'Defaults:vagrant !requiretty' >>  /etc/sudoers.d/vagrant'

**Comment by snufalufagus** [comment]
This requiretty/vagrant issue is a major pain. I am still a puppet novice but the saz-sudo module looks to be one of the better forge module options that has with Hiera capability. Could a true/false parameter be added in enable/disable(comment out) requiretty for Centos/RHEL flavors?

the following doesn't seem to work for me:
 config.vm.provision "shell", :inline => "echo 'Defaults:vagrant !requiretty' >>  /etc/sudoers.d/vagrant"

**Comment by vindir** [comment]
This is pretty easy to fix by adding a hiera entry overriding the default.  Something like the below makes it a non-issue when added to your hieradata.

sudo::configs:
    'requiretty':
        'content'   : "Defaults   !requiretty"
    'visiblepw':
        'content'   : "Defaults   visiblepw"

**Comment by vindir** [comment]
Also worth noting... if this issue is resolved, it should probably remove the visiblepw default entries in all of the centos files as well since they are related configs.

**Comment by SydOps** [comment]
@vindir 
Good work, anyway, it is better solution than mine.

**Comment by saz** [comment]
This should be fixed in the current master
