### ISSUE TITLE
Trailing commas in metadata.json

### ISSUE THREAD

**Issue by lvlie** [saz/puppet-sudo#110]
Hi,

First off, thanks for the awesome module :) There is one issue which we came accross, the metadata.json has trailing commas inside the bracketed parts on line 20 and line 23. They should not exist and json parsers (like jq) fail on it. I could write a pull request but such a small issue is probably easier fixed without :) 

Thanks!
- Leon

**Comment by pbyrne413** [comment]
There are actually two pull requests already for this issue, so it is just a matter of when that gets merged back in.

**Comment by lvlie** [comment]
Oops, missed that. Thanks for the heads up.
