### ISSUE TITLE
sudoers + ldap

### ISSUE THREAD

**Issue by Rocco83** [saz/puppet-sudo#115]
Hi,

this package does not include, imo, the support for sudoers.
Do you confirm?

If so, i can write a patch.

2 paths:
* automatic
* hiera

automatic means find for ldap or sss on nsswitch, plus using specific package (ie: sudo-ldap on debian)
hiera means flag to pull ldap support, and handle only the package.

**Comment by saz** [comment]
I'm open for a pull request.
