### ISSUE TITLE
Namespacing Issue in config.pp

### ISSUE THREAD

**Issue by vindir** [saz/puppet-sudo#118]
In puppet 2.7 the forced basing of the namespacing for ::sudo::conf on line 20 of config.pp causes the tag errors below.  It works fine without rooting that call though.  I assume it's not necessary in newer versions either.  I've added #117 with a simple fix.  Is it possible to make the change in this PR or is there another possible workaround?

Puppet 2.7 Failure:
Invalid tag "::sudo::conf" at /etc/puppet/modules/sudo/manifests/configs.pp:20 on node jho.dev.localdomain.com

**Comment by saz** [comment]
This is resolved in the current master

**Comment by andrewj100** [comment]
Hit a problem first time using saz-sudo

Puppet v2.7.23
saz-sudo-3.1.0.tar.gz
puppetlabs-stdlib-4.9.0.tar.gz
Hiera - not installed

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Unknown function hiera_hash at /etc/puppet/modules/sudo/manifests/configs.pp:20 on node

As a quick workaround I've commented out the $configs = hiera_hash('sudo::configs', $configs_hash) line as the next line down is checking if $configs is empty.

Is it possible to check if the hiera_hash function exists before calling it?
