### ISSUE TITLE
visudo check may give false sense of syntax correctness

### ISSUE THREAD

**Issue by somic** [saz/puppet-sudo#125]
Before https://github.com/saz/puppet-sudo/pull/99, visudo checked entire sudo config. In that PR it started checking just a single config file being added/modified.

Unfortunately, this may give a false sense of syntax correctness. For example, if your sudo::conf { 'foo': } redefines Cmnd_Alias that already is defined somewhere else, current file will pass visudo syntax checks but sudo config as a whole will be broken.

Maybe consider changing visudo exec to be what it used to be before PR 99 and add validate_cmd on File resource inside sudo::conf? I am not yet convinced it's the best way forward though.

**Comment by saz** [comment]
This is configurable in the current master.
