### ISSUE TITLE
Error: /Stage[main]/Sudo/Augeas[includedirsudoers]: Could not evaluate: Saving failed, see debug

### ISSUE THREAD

**Issue by mukeshdevops** [saz/puppet-sudo#128]
"name": "saz-sudo",
  "version": "3.0.9",

Puppet augeas lens fails to parse the following line in sudo file:

Cmnd_Alias BALANCE = /sbin/lvm lvdisplay -m, /sbin/scsi_id -p 0x83 -s /block/sd* -g, /lib/udev/scsi_id --page=0x83 --whitelisted --device=/dev/sd*, /sbin/dmsetup deps, /sbin/fdisk -lu, /sbin/mdadm -D /dev/sd*, /usr/local/bin/scli -z all

Warning: Augeas[includedirsudoers](provider=augeas): Loading failed for one or more files, see debug for /augeas//error output 
Debug: Augeas[includedirsudoers](provider=augeas): /augeas/files/etc/sudoers/error = parse_failed 
Debug: Augeas[includedirsudoers](provider=augeas): /augeas/files/etc/sudoers/error/pos = 3549 
Debug: Augeas[includedirsudoers](provider=augeas): /augeas/files/etc/sudoers/error/line = 105 
Debug: Augeas[includedirsudoers](provider=augeas): /augeas/files/etc/sudoers/error/char = 0 
Debug: Augeas[includedirsudoers](provider=augeas): /augeas/files/etc/sudoers/error/lens = /var/opt/lib/pe-puppet/lib/augeas/lenses/fixedsudoers.aug:509.10-.70: 
Debug: Augeas[includedirsudoers](provider=augeas): /augeas/files/etc/sudoers/error/message = Iterated lens matched less than it should 
Debug: Augeas[includedirsudoers](provider=augeas): Will attempt to save and only run if files changed 
Debug: Augeas[includedirsudoers](provider=augeas): sending command 'set' with params ["/files/etc/sudoers/#includedir", "/etc/sudoers.d"] 
Debug: Augeas[includedirsudoers](provider=augeas): Closed the augeas connection

augeas tool parse it successfully with the standard lense /usr/share/augeas/lenses/dist/sudoers.aug shipped with augtool 1.2.0.

**Comment by tosmi** [comment]
you do not mention on what distribution this happens... (rhel, debian). please also specify the exact version you are using. i'm not sure the the lense from augeas 1.2.0 is going to work on all distributions, especially the older ones (e.g. rhel 5).

**Comment by mukeshdevops** [comment]
The issue was detected on rhel5. I agree that we should include the standard souders lense for rhel5.
