### ISSUE TITLE
right operand of + is not a number at sudo/manifests/params.pp:13

### ISSUE THREAD

**Issue by zeha** [saz/puppet-sudo#137]
This line (manifests/param.pp:13):
```
if (0 + $::operatingsystemmajrelease >= 7) {
```

breaks on Debian hosts that are set to use unstable/sid, because `operatingsystemmajrelease` will not be a number (but rather `stretch/sid` until the next release).

**Comment by deogracia** [comment]
It breaks even on wheezy
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.9 (wheezy)
Release:	7
Codename:	wheezy
```

**Comment by deogracia** [comment]
I upgrade my master from puppet and client from 2.7 to puppet 3.8.3. it works  :D 
My bad ...

**Comment by saz** [comment]
This issue should be resolved in the current master
