### ISSUE TITLE
Unknown function hiera_hash

### ISSUE THREAD

**Issue by ubellavance** [saz/puppet-sudo#145]
Puppet v2.7.25 (server)
Puppet 3.8 (client)
saz-sudo-3.1.0.tar.gz
Hiera - not installed

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Unknown function hiera_hash at /etc/puppet/modules/sudo/manifests/configs.pp:20 on node

As a quick workaround I've commented out the $configs = hiera_hash('sudo::configs', $configs_hash) line as the next line down is checking if $configs is empty.

Is it possible to check if the hiera_hash function exists before calling it?

Thanks,

**Comment by tosmi** [comment]
please check the version requirements by puppetlabs

https://docs.puppetlabs.com/guides/install_puppet/upgrading.html#always-upgrade-the-puppet-master-first

so running an old master with newer clients is not supported. i would suggest upgrading you master asap.

i'm also not aware of a way to check if a function is defined before calling that particular function. 

toni
