### ISSUE TITLE
Puppet 4 - Ubuntu 16.04 - /etc/sudoers does not get overwritten.

### ISSUE THREAD

**Issue by craigmonson** [saz/puppet-sudo#160]
Ubuntu - 16.04
Puppet - 4.5.3
Running via test kitchen - 1.9.1
box: "ubuntu/xenial64"
box_version: "20160606.1.0"

doing: `include ::sudo` or `class { 'sudo': }` or `class { 'sudo': config_file_replace => true }` does not purge /etc/sudoers as noted in the documentation.

There's also no mention (obvious maybe) in the puppet run output for /etc/sudoers

**Comment by borian** [comment]
I am having the same issue

**Comment by jg-development** [comment]
Hi,
the problem ist in the config.pp
```
$configs = hiera_hash('sudo::configs', $configs_hash)
```
Hiera with puppet 4 now uses lookup
new example with deep merge:
```
$configs = lookup('sudo::configs', Hash, {"strategy" => "deep", "merge_hash_arrays" => true}, $configs_hash)
```
Greetings Jan

**Comment by law** [comment]
I am also having this same issue

**Comment by saz** [comment]
Any news on this?

**Comment by jg-development** [comment]
I think I can try it today and give u some feedback

**Comment by jg-development** [comment]
Hi,
I tried with the following:
Vagrant Box with Ubuntu 16.04
Puppet 4.8.1
sudo version 4.1.0

sudo.yaml
```
---
classes:
    - sudo
sudo:
  ensure: present
sudo::configs:
  'ubuntu_admin':
    content: "ubuntu ALL=(ALL) NOPASSWD: ALL"
    priority: 10
```
default.pp
```
include ::sudo
include ::sudo::configs
```
Result:
The sudoers file does not get overwritten and the configs are not included.
With the modification from above it does work:
```
$configs = lookup('sudo::configs', Hash, {"strategy" => "deep", "merge_hash_arrays" => true}, $configs_hash)
```
Greetings
Jan

**Comment by hboetes** [comment]
I just tried it again with puppet-4.10.0 and ubuntu 16.04.02
Now the proposed workaround also doesn't work.

**Comment by template-provider** [comment]
hi ... which version do you mean?
works for me:
```
root@tp64:/home/ubuntu# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```
```
ubuntu@tp64:~$ puppet agent --version
4.10.0
```

**Comment by template-provider** [comment]
Tested with module version 4.10

**Comment by hboetes** [comment]
Hello @jg-development , I got exactly the same version as you have. But I am talking about replacing `/etc/sudoers` and not `/etc/sudoers.d/*` as is stated in the initial message.
Managing `/etc/sudoers.d/*` works great, and has always worked. Managing `/etc/sudoers` does not work for me. Even with the before mentioned workaround.

**Comment by jg-development** [comment]
Hi @hboetes ,
/etc/sudoers is replaced for me too.
```
root@tp64:/home/ubuntu# cat /etc/sudoers
# file managed by puppet (unless config_file_replace=false)
#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults	env_reset
Defaults	mail_badpass
Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root	ALL=(ALL:ALL) ALL

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Allow members of group sudo to execute any command
%sudo	ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d
```
Greetings Jan

**Comment by hboetes** [comment]
ok, let's explain what I did, here is my config:
```                                                                                                                                            
  class { 'sudo':                                                                                                                                                                              
  }                                                                                                                                                                                            
  sudo::conf { 'admins':                                                                                                                                                                       
    priority => 10,                                                                                                                                                                            
    content  => "%sudo ALL=(ALL:ALL) ALL",                                                                                                                                                     
  }                                                                                                                                                                                            
  ```
And I made a few modifications in `templates/sudoers.erb`

The changes in the latter are ignored. Am I doing something wrong or is that how I should do it and I should expect my changes to `templates/sudoers.erb` to be roled out?

**Comment by jg-development** [comment]
Hi,
I only use the hiera lookup as seen above with:
```
  include ::sudo
  include ::sudo::configs
```
Every change in the template file results in a new sudoers files. From my side with the pull request everything ist ok. Could you test it with a hiera lookup?
Greeting Jan

**Comment by hboetes** [comment]
No I can't, I haven't used hiera and setting it up takes more time than I'm willing to spend.

**Comment by saz** [comment]
Please give the current master a try
