### ISSUE TITLE
config_dir not overwritten

### ISSUE THREAD

**Issue by redno2** [saz/puppet-sudo#162]
Despite set config_dir when the class is loaded, the file and config is not tested and created on the right place :
Same effect on solaris 10 and ubuntu 14.04 and I use hiera to set sudo::configs

 #Init class with some defaults config for solaris  
  case $::osfamily {
    'Solaris': {
      class { '::sudo':
        purge               => true,
        config_file_replace => true,
        package             => 'SMCsudo',
        package_ensure      => 'present',
        package_source      => "URL/package,
        config_file         => '/usr/local/etc/sudoers',
        config_dir          => '/usr/local/etc/sudoers.d/',
        package_admin_file  => '/var/sadm/install/admin/puppet',
      }
      include sudo::configs
    }
    default: {
      class { '::sudo':
        purge               => true,
        config_file_replace => true,
        config_dir          => '/etc/sudoers.test/',
      }
      include sudo::configs
    }
  }

Thank you

**Comment by saz** [comment]
Can you try it with the newest release, if this is still happening for you?

**Comment by saz** [comment]
Any news on this?
