### ISSUE TITLE
How do I  configure sudo rules in /etc/sudoers instead of sudoers.d 

### ISSUE THREAD

**Issue by qafro1** [saz/puppet-sudo#169]
Please  I want all of the sudoers config to go into the /etc/sudoers file and not /etc/sudoers.d 
using this module.

Any ideas?

**Comment by saz** [comment]
It's not possible with my module. 




Sent using Boxer

On 7 Dec 2016 10:11 AM, qafro1 <notifications@github.com> wrote:

Please I want all of the sudoers config to go into the /etc/sudoers file and not /etc/sudoers.d
using this module.

Any ideas?

**Comment by felipe1982** [comment]
would creating a template help? I'm only just beginning to use this module..... sorry.

**Comment by qafro1** [comment]
How would one create a template for it?

**Comment by saz** [comment]
It's not possible at all to get the configuration inside the sudoers file.
This module is not designed in this way.
It's designed to split the configuration into multiple files in /etc/sudoers.d

What's the reason for your requirement?

**Comment by felipe1982** [comment]
You might check out justinclayton-sudo
