### ISSUE TITLE
Puppet 4 support

### ISSUE THREAD

**Issue by michaelkrieg** [saz/puppet-sudo#172]
Since I upgraded to Puppet version 4, this Hiera configuration does not work anymore. Example:

```
sudo::config_file_replace: false
sudo::configs:
    'admin':
        'content'   : "%admin ALL=(ALL) NOPASSWD: ALL"
        'priority'  : 10

```
In version 3 a file under /etc/sudoers.d/ is placed with the correct name "10_admin".
Now the module runs without any error but no more files anymore under sudoers.d/

Any ideas?

**Comment by ubellavance** [comment]
- Is the class still in /var/lib/puppet/classes.txt (or equivalent)?
- Have you run puppet in debug mode on the client?

**Comment by michaelkrieg** [comment]
Puppet runs with apply:
```
FACTER_role=${ROLE} puppet apply --verbose --report --show_diff --summarize \
	    --modulepath "${repo_dir}/site:${repo_dir}/modules:/etc/puppetlabs/code/modules" \
	    --environmentpath "/tmp" \
	    --hiera_config="${repo_dir}/hiera-local.yaml" \
	    --config_version="${config_version}" \
	    --detailed-exitcodes $manifest \
      --write-catalog-summary
```

(I left my variables there, but ....)

dumping relevant resources.txt entries:
file[/etc/sudoers.d]
file[/etc/sudoers]
package[sudo]

dumping relevant classes.txt entries:
sudo
sudo::configs
sudo::package
sudo::params

**Comment by michaelkrieg** [comment]
ok.... my fault.
please ignore the report here. 
it was due to invalid YAML file indentation. 👎 

So: no bug, works!
