### ISSUE TITLE
4.0.0 broken on ArchLinux - params::package_ldap undefined

### ISSUE THREAD

**Issue by jantman** [saz/puppet-sudo#173]
I only discovered this because I'm using this module in one of my own, and depend on ``>=3.0.0 <4.0.0`` but left my .fixtures.yml with just the git repo, so it's pulling in master.

It appears that, on Archlinux, 4.0.0 now fails because [init.pp](https://github.com/saz/puppet-sudo/blob/master/manifests/init.pp#L87) has ``$package_ldap = $sudo::params::package_ldap`` but params.pp doesn't define $package_ldap in the [Archlinux block](https://github.com/saz/puppet-sudo/blob/master/manifests/params.pp#L172).

**Comment by saz** [comment]
Thanks for pointing this out. Can you give the current master a try, if it's working as expected?

**Comment by jantman** [comment]
Looks good to me, thanks so much!
