### ISSUE TITLE
check-syntax statement not working on FreeBSD.

### ISSUE THREAD

**Issue by madelaney** [saz/puppet-sudo#175]
Using version 4.1.0 of the module, I noticed that the execute statement `exec {"sudo-syntax-check for file ${cur_file}":` results in the following puppet error:
`Could not find command 'visudo'`.

I believe this is due to the fact that, on FreeBSD, the command visudo is installed into '/usr/local/sbin' and the execute path is set to only '/bin', '/sbin', '/usr/bin', '/usr/sbin'.

**Comment by stblassitude** [comment]
See pull request #178.

**Comment by saz** [comment]
Fixed with commit d41e6dad71e34aa8f1360fee6ce934a9fd247435
