### ISSUE TITLE
secure_path doesn't have puppet binary

### ISSUE THREAD

**Issue by disassembler** [saz/puppet-sudo#177]
This commit was made a while back:

https://github.com/saz/puppet-sudo/commit/b98b1249ce7a97bbd1dd6cb5d5415b0ee8b7a258

But it does nothing, because /etc/sudoers uses static files and those static files haven't had the path updated. (in files directory).

To allow running `sudo puppet agent -t` works without having specify the full path every time, /etc/sudoers should be updated to contain the secure_path.

**Comment by saz** [comment]
Fixed with commit cb8d1165e00ab9ecbd7c06f0b2bf55d6dab51a98
