### ISSUE TITLE
Gentoo not supported but code references non-existent Resource type

### ISSUE THREAD

**Issue by tb3088** [saz/puppet-sudo#179]
Doesn't look like Gentoo was ever supported (or perhaps very, very long time ago) and indeed metadata.json hasn't indicated support for a long time now, but line ~40 in package.pp has a case statement not commented out that relates to Gentoo, Portage and  Resource 'package_use'.

please remove or otherwise comment out to keep Validation from showing spurious errors.

**Comment by saz** [comment]
I'm pretty sure Gentoo is supported, as I'm using this module on systems running Gentoo :-)

I'll clean this up to make it clear.
