### ISSUE TITLE
includedir but commented out, what's the point?

### ISSUE THREAD

**Issue by lkthomas** [saz/puppet-sudo#198]
templates/sudoers.ubuntu.erb:

#includedir <%= @config_dir %>
<% @extra_include_dirs.each do |include_dir| -%>
#includedir <%= include_dir %>
<% end if @extra_include_dirs -%>

so even I use extra_include_dirs, it will still commented out, what's the point of having that in-place? Shall we change erb template? Originally Ubuntu sudoers file already have that directory commented out, maybe we could introduce a switch to enable includedir instead of hard code into erb template ?

**Comment by saz** [comment]
From the man page:
```
Including other files from within sudoers
It is possible to include other sudoers files from within the sudoers file currently being parsed using the #include and #includedir directives. 
```
It's expected like this and working without a problem.
