### ISSUE TITLE
ensure_packages(): Wrong number of arguments given (2 for 1) at /etc/puppet/modules/sudo/manifests/package.pp:77

### ISSUE THREAD

**Issue by phar1no** [saz/puppet-sudo#199]
With this setttings:

```
class { 'sudo':
        purge               => false,
        config_file_replace => false,
  }

  sudo::conf { 'user':
        priority    => 10,
        content     => "user ALL=(ALL) NOPASSWD: ALL",
  }
```

I get the error:

> Error: Could not retrieve catalog from remote server: Error 400 on SERVER: ensure_packages(): Wrong number of arguments given (2 for 1) at /etc/puppet/modules/sudo/manifests/package.pp:77 on node some.node.domain

But if i comment next lines in /etc/puppet/modules/sudo/manifests/package.pp, all works fine!

```
 74     }
 75     default: {
 76         #if $package != '' {
 77         #  ensure_packages([$package], {'ensure' => $package_ensure})
 78         #}
 79     }
```
saz-sudo-4.2.0
puppet-server-3.7.1-1.el6.noarch
clients:
 RHEL5,6,7
 Ubuntu1604

**Comment by saz** [comment]
This should be fixed in the current master.
