### ISSUE TITLE
Puppetlabs/apache and sudo 

### ISSUE THREAD

**Issue by sudodevnull** [saz/puppet-sudo#202]
I am getting a dependency cycle between your module and the puppetlabs/apache module.  Hoping you can help identify/resolve the problem here:

Failed to apply catalog: Found 1 dependency cycle: (Anchor[sudo::begin] => Class[Sudo] => Stage[postfeatures] => Stage[hieraclasses] => Class[Apache] => Package[httpd] => File[headers.load] => Apache::Mod[headers] => Class[Apache::Mod::Headers] => Stage[main] => Stage[postfeatures] => Class[Sudo] => Anchor[sudo::begin]) Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz

Here is the digraph: 
digraph Resource_Cycles { 
label = "Resource Cycles" 
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Exec[mkdir /etc/httpd/conf.modules.d]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Linuxauth]" -> "Class[Linuxauth]" -> "Stage[postfeatures]" 
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Exec[mkdir /etc/httpd/conf.modules.d]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Sudo]" -> "Anchor[sudo::begin]" 
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Package[httpd]" -> "Exec[mkdir /etc/httpd/conf.modules.d]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Sudo]" -> "Anchor[sudo::begin]" 
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Package[httpd]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Linuxauth]" -> "Class[Linuxauth]" -> "Stage[postfeatures]" 
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Package[httpd]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Sudo::Configs]" -> "Class[Sudo::Configs]" -> "Stage[postfeatures]" 
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Package[httpd]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Sudo::Params]" -> "Class[Sudo::Params]" -> "Stage[postfeatures]" 
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Package[httpd]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Sudo]" -> "Anchor[sudo::begin]" 
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Package[httpd]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Sudo]" -> "Anchor[sudo::end]" -> "Class[Sudo]" 
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Package[httpd]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Sudo]" -> "File[/etc/sudoers.d/]" -> "Class[Sudo]" 
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Package[httpd]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Sudo]" -> "File[/etc/sudoers]" -> "Class[Sudo]" 
}

**Comment by sudodevnull** [comment]
Here is our current wrapper class for your module:
`# manage sudo files
class linuxauth::sudo {
  $sudoers_env          = $facts['tier'] ? {
    /(uat|dev|sit)/     => 'nonprod',
    /(prod|dr)/         => 'prod',
  }

  $sudoers_data         = lookup('linuxauth::sudoers')

  $sudoers_base         = $sudoers_data['base'] ? {
    undef               => {},
    default             => $sudoers_data['base'],
  }

  $sudoers_applications = $sudoers_data[$sudoers_env][$::node_type] ? {
    undef               => {},
    default             => $sudoers_data[$sudoers_env][$::node_type],
  }

  $sudoers              = $sudoers_base + $sudoers_applications

  # Pretty print Hiera data
  # $hieradata            = inline_template('<%- require "json" -%><%= JSON.pretty_generate(@sudoers) %>')
  # notice $hieradata

  # Disable purging of sudoer data while under development
  contain class { '::sudo':
    purge               => false,
    config_file_replace => false,
  }

  # IN PROGRESS: Sudoers files need to adhere same tier/app specific matrix as the sssd configuration
  if ! $sudoers.empty {
    $sudoers.each |$sudoer, $config| {
      ::sudo::conf { $sudoer :
        content        => $config[content],
        sudo_file_name => $sudoer,
      }
    }
  }
}`

**Comment by sudodevnull** [comment]
This is for rhel7

**Comment by sudodevnull** [comment]
I believe it is due to your anchor

**Comment by saz** [comment]
This should be fixed in the current master

**Comment by sudodevnull** [comment]
can I asked what you did to resolve? I have not tested yet...
