### ISSUE TITLE
incorrect use of 'define' in conf.pp

### ISSUE THREAD

**Issue by ponaboy** [saz/puppet-sudo#206]
importing this module into Foreman fails to pull in the sudo::conf class. line 40 of 'conf.pp' start with the directive define() instead of class().

not sure if this is a typo or intentional. swapping out directives resolves the issue.

**Comment by saz** [comment]
This is no mistake at all, as this needs to be a defined type: https://puppet.com/docs/puppet/4.10/lang_defined_types.html
