### ISSUE TITLE
Module generates deprecation warnings with puppet 4.8 (debian stretch)

### ISSUE THREAD

**Issue by Kyoshiro-san** [saz/puppet-sudo#208]
Hi,

The module generates deprecation warnings with puppet 4.8 (debian stretch).

> This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README. at ["/etc/puppet/code/modules/sudo/manifests/init.pp", 101]:["/etc/puppet/code/modules/profile/manifests/centralnode.pp", 17]

> This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Hash. There is further documentation for validate_legacy function in the README. at ["/etc/puppet/code/modules/sudo/manifests/configs.pp", 13]:["/etc/puppet/code/modules/sudo/manifests/init.pp", 168]

> This method is deprecated, please use match expressions with Stdlib::Compat::Array instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/etc/puppet/code/modules/sudo/manifests/conf.pp", 90]

I'll open a pull request with a fix.
Cheers !

**Comment by Kyoshiro-san** [comment]
Opened PR #209

**Comment by saz** [comment]
This should be fixed in the current master

**Comment by Kyoshiro-san** [comment]
Thank you :)
