### ISSUE TITLE
Template users_groups.erb is broken

### ISSUE THREAD

**Issue by gvdijnsen** [saz/puppet-sudo#212]
While adding groups, an extraneous '%' is added at the begin of the line. Leading to something like:

%%mygroup

This does not work. This should be the result:

%mygroup

On line 8 of the template, removing the first % sign fixes the problem

**Comment by saz** [comment]
Which puppet version and Ruby version are you running?


Because of https://github.com/saz/puppet-sudo/commit/6dc14b90649bf03cfb02f19e494a5c8263624fe4 the second percentage sign was added.

**Comment by gvdijnsen** [comment]
We are running:
ruby 2.3.1p112
puppet 4.10.9

**Comment by saz** [comment]
This issue has been resolved in the current master
