### ISSUE TITLE
Feature Request: Ability to add additional paths to secure_path

### ISSUE THREAD

**Issue by jameskirsop** [saz/puppet-sudo#220]
I'd love to be able to add a list of additional paths to the sudoers file to have a standard path variable across our fleet.

**Comment by ubellavance** [comment]
Are you planning on managing your sudoers config with puppet for all your fleet?

**Comment by jameskirsop** [comment]
Yep! That's the plan for our deployment where we're using puppet.

We'd like some particular paths included to simplify administration for our admins.

If I get time, I might try and code something up and put in a PR. For the minute I'll just keep using the full path to the binaries we're running.

**Comment by ubellavance** [comment]
If it's easier, you can simply edit the template on your puppet server (if you're using a server). But make sure you remember that if you upgrade the module, your change will be overwritten, but I assume that would be temporary.

**Comment by saz** [comment]
Maybe `content` parameter on class `sudo` will help you to get this working for you for now.
Just pass in a different template for the sudoers file.

@jameskirsop If you're able to find the time for a PR, this would be great!

**Comment by saz** [comment]
This issue is now fixed. There will be a new release soon.
