### ISSUE TITLE
Class[Sudo]: parameter 'purge_ignore' expects a value of type Undef or String, got Tuple

### ISSUE THREAD

**Issue by minorOffense** [saz/puppet-sudo#221]
Our puppet class has ``include ::sudo`` at the top and in our hiera file we have the following:

```yaml
## Sudo Settings
sudo::purge: false
sudo::purge_ignore:
  - vagrant
```

When we upgraded to 5.0.0 we started to get that error in the title. Looking at the definition it looks correct for purge_ignore as it will take an array or a string. I guess I'm just looking for some feedback or ideas as to why this would cause that issue.

**Comment by mlg9000** [comment]
We too have this issue with 5.0.0.

**Comment by hbuckle** [comment]
If you download the 5.0.0 release it appears the code to make it accept an array is missing

``
Optional[String]         $purge_ignore        = undef,
``

**Comment by minorOffense** [comment]
I guess we need a 5.0.1 release then.

**Comment by saz** [comment]
This should be resolved in the current master and soon published with a new release
