### ISSUE TITLE
Do not remove systemctl alias for EL 7

### ISSUE THREAD

**Issue by ttres** [saz/puppet-sudo#224]
EL 7 systems `/etc/sudoers` comes with some `systemctl` commands, by default, in `SERVICES` alias, that should not be erased:
```
# Cmnd_Alias SERVICES = /sbin/service, /sbin/chkconfig, /usr/bin/systemctl start, /usr/bin/systemctl stop, /usr/bin/systemctl reload, /usr/bin/systemctl restart, /usr/bin/systemctl status, /usr/bin/systemctl enable, /usr/bin/systemctl disable
```
Expected result: alias is not changed
Actual result: alias is rewritten and `systemctl` commands are removed

**Comment by mathse** [comment]
+1
