### ISSUE TITLE
do not fail without sudoversion fact on modern os's

### ISSUE THREAD

**Issue by SimonPe** [saz/puppet-sudo#226]
The main problem here is that any module depending on puppet-sudo has to manually specify the sudoversion fact in its rspec tests because otherwise it will fail.
since `versioncmp` fails hard when you pass it `undef` an alternative would be something like:
```
if (!$::sudoversion or versioncmp($::sudoversion, '1.7.2p1') < 0)
```
this would still print the warning, but not fail the manifest compilation.

**Comment by saz** [comment]
I'm happy for any PR resolving this issue.

**Comment by saz** [comment]
If this issue still exists, feel free to send in a pull request. Closing this now.
