### ISSUE TITLE
Updating requirements

### ISSUE THREAD

**Issue by jehane** [saz/puppet-sudo#232]
Hi, 

The puppetlabs-sdtlib module required by your sudo module is actually in 5.2.0 version. Requirements for the sudo module is puppetalbs-stdlib >=2.6.0 < 5.0.0
Can you update the requirements of your module so it's easier to update ? 

Regards

**Comment by jehane** [comment]
I have created a pull request ( https://github.com/saz/puppet-sudo/pull/234 )

**Comment by saz** [comment]
Fixed in master
