### ISSUE TITLE
Rspec testing Failure/Error:   Evaluation Error: Unknown function: 'ensure_packages'. package.pp:77:9 

### ISSUE THREAD

**Issue by zhasaan** [saz/puppet-sudo#233]
I am not expert , however trying to use this Puppet module inside my code and getting following error

Failure/Error: it { is_expected.to compile.with_all_deps }
       error during compilation: Evaluation Error: Unknown function: 'ensure_packages'. at /home/vagrant/d362158/bmc_discovery/spec/fixtures/modules/sudo/manifests/package.pp:77:9 on node telstra-o71lqeu.wg.dir.telstra.com

This function seems to be in package.pp file which is point to paramater $package_ensure, And I am using this parameter in my code

class { 'sudo': 
  package_ensure =>  present,
  ldap_enable =>  true,
  }

vagrant@telstra-o71lqeu bmc_discovery]$ tail spec/fixtures/modules/sudo/manifests/package.pp
        package_admin_file => $package_admin_file,
      }
    }
    default: {
      if $package != '' {
        ensure_packages([$package], {'ensure' => $package_ensure})
      }
    }
  }
}

What I am missing here? Any help shall be greatly appreciated.
Regards,
Zia-ul-Hassan

**Comment by ubellavance** [comment]
Hi, what is the version of: puppet, OS, this module?

**Comment by zhasaan** [comment]
Puppet: v 4.10.12
OS: RHEL7
Module Version: 5.0.0

**Comment by zhasaan** [comment]
Also note that my development server has following in the metadata.jason and .fixtures.yml files
-----------------------------------------------
 "dependencies": [
    {
      "name": "puppetlabs-stdlib",
      "version_requirement": ">= 1.0.0"
    },
    {
      "name": "saz-sudo",
      "version_requirement": ">= 5.0.0"
    }
  ],
  "data_provider": null
}
--------------------------------------------------
fixtures:
  forge_modules:
    stdlib: "puppetlabs-stdlib"
    stdlib: "saz-sudo"
  symlinks:
    bmc_discovery: "#{source_dir}"
----------------------------------------------------

**Comment by zhasaan** [comment]
Sorry I found my issue , where I made typo in .fixtures.yml file
forge_modules:
stdlib: "puppetlabs-stdlib"
**sudo: "saz-sudo"**
symlinks:
bmc_discovery: "#{source_dir}"
