### ISSUE TITLE
Feature Request: Allow default settings from hiera

### ISSUE THREAD

**Issue by andylytical** [saz/puppet-sudo#239]
Some settings in the provided templates for `/etc/sudoers` are insufficient to meet our security guidelines.

Would be nice to allow passing default values via class parameters.

Our current workaround is to replace `$sudo::content` with just the `#includedir` part and then put all our default settings in hiera in `sudo::configs` with a priority of 0.

**Comment by andylytical** [comment]
Similar to #220

**Comment by saz** [comment]
As there's more discussion on #220 I'll close this issue, but it's referenced on the other issue.

If someone sends in a PR, that would be great!
