### ISSUE TITLE
rhel 8 support is missing, PRs have been submitted

### ISSUE THREAD

**Issue by ckxng** [saz/puppet-sudo#250]
rhel 8 support is missing
a template needs to be added for it.

at the time i'm submitting this ticket, two PRs already exist.
https://github.com/saz/puppet-sudo/pull/245
https://github.com/saz/puppet-sudo/pull/247

**Comment by jehane** [comment]
His the module still maintained ? Can you release a new version with CentOS/RHEL 8 support ?

**Comment by saz** [comment]
I'll release a new version asap

**Comment by saz** [comment]
#247 is merged now
