### ISSUE TITLE
unable to use hiera.yaml with module profile

### ISSUE THREAD

**Issue by gerbdla** [saz/puppet-sudo#256]
I believe this a is a problem or at least I am unable to get hiera to work.  Here is my setup

inside module_profile
class mc_profiles::sudo () {
  
  class { "::sudo":
    # leave sudoers as is
   purge               => false,
   config_file_replace => false,
  }
}
I tried several configurations none of which worked

hiera.yaml in module_profile
sudo::configs:
    'dave':
        'ensure'    : 'absent'
        'source'    : 'puppet:///files/etc/sudoers.d/users/dave'

or
sudo::configs:
    '**module_profile::dave**':
        'ensure'    : 'absent'
        'source'    : 'puppet:///files/etc/sudoers.d/users/dave'

Any ideas about how to use sudo module hiera.yaml.

**Comment by gerbdla** [comment]
Question:  Is it possible to use sudo with a parent class that instantiates sudo and uses hiera.yaml?

**Comment by saz** [comment]
I'm not sure, if I get that right, but I think you're trying to use data in modules? If that's the case, I'd guess that you have to add parameters to your class and pass them on to the sudo module.

**Comment by gerbdla** [comment]
If I understand this correctly you can put this into your a hiera file such as common.yaml and it will automatically create the users without having to use sudo::conf resource?  The key name has to be sudo::config correct?  
If so, I guess I will have to make them params in the class and pass them to the sudo::config resource.  
It would be nice to be able to put everything in the hiera data if I use a parent class structure example like class mc_profiles { class sudo }}

I see this line in init.pp 
Hash                                      $configs             = {},

I don't see where the code is that extracts the sudo:conf from a hiera file.  can you show me the code on how you are doing it?

Thanks

Dave

**Comment by saz** [comment]
Have you found a solution for your issue?
