### ISSUE TITLE
is this still maintained

### ISSUE THREAD

**Issue by codylane** [saz/puppet-sudo#257]
Hello @saz,

Thank you so much for creating this module.  I've used it so much over the years.  

I'm just curious if this module is still under active development?  If not, I'm wondering how I can help?  I'm happy to start addressing outstanding issues and PRs if you think that might be a good place to start?

Again, thank you so much for this module and I look forward to hearing from you how I can help.

**Comment by saz** [comment]
Thanks for reaching out and the kind words! This is what is missing from time to time.

Yes, I'm still maintaining this module and I'm more than happy for any review of issues or pull requests.
That's definitely a good point to start.

I'm trying to be more active again and have a look at all the open things. Is there anything particular of interest to you?

**Comment by codylane** [comment]
Hi @saz - Thank you as well for the kind reply. I was hoping I had the wording ok to not offend you because you've done so many awesome things with this module.

That said, there is nothing specific at the moment that I need addressed but I may in the future as I start to ramp back up with puppet 6.  I was more or less concerned since there hasn't been a release since 2019 but I understand that not a lot changes with sudoers so I just wanted to do my part and at least ask how I can help in my spare personal time.  I'll start trying to address some of the open issues as I have spare personal time in the next few weeks.

Thanks again for your quick reply and I look forward to helping as best as I can. (if possible).

**Comment by codylane** [comment]
Hi Folks,

I've not forgotten about this, i'm just a little over anxious with how much free time I have to contribute.  I promise I will. I'm hoping things will slow down a little now that we are in holiday season and hope that I'll have some free cycles to help get a few issues addressed here.  

I hope you all are well, stay safe and talk to you soon.

**Comment by saz** [comment]
@codylane I'll close this, as it's not a real issue (I'm still happy of any reviews of PRs or issues :-))
