### ISSUE TITLE
Facter error on Windows

### ISSUE THREAD

**Issue by jovandeginste** [saz/puppet-sudo#258]
First, thanks for all your work on the puppet modules! I use some of them, and appreciate it! I hope I have contributed to your projects at some point, but I'm not sure 😄 

I run into a weird minor issue. I'm using the same Puppet stack to configure all my home devices, including my Windows gaming laptop. I'm a strange person, maybe. I'm also using this module.

While the module is not included on the Windows devices, the facts are added automatically.

My gaming laptop happens to have a utility called "sudo" which basically wraps whatever is "sudo" in Windows land. That utility does not have the `-V` parameter.

So now, this module throws an error:
> Error: Facter: error while resolving custom fact "sudoversion": undefined method `[]' for nil:NilClass

There are many ways to solve this, but I see two ways this can be properly solved inside the sudo module:

1. add a `confine` statement to the fact, so it doesn't run on Windows
1. add some simple error handling at [this line](https://github.com/saz/puppet-sudo/blob/ee2670f220c3327d9603f772abb5081cc679da9b/lib/facter/sudoversion.rb#L6)

I'm willing to create a PR solving this in one of the above ways, but would like feedback first!

Thanks!

**Comment by saz** [comment]
First: Thanks! :smile: 

I'd prefer the confine, as the fact shouldn't be running on Windows at all.
I'm happy of a PR!

**Comment by jovandeginste** [comment]
Please find my PR; wondering about the CI tests, however ...

**Comment by saz** [comment]
@jovandeginste This issue should be resolved in master. Please give it a try.
