### ISSUE TITLE
Dependency pinning resolves version 4.1.0 with new stdlib version 7.0.0

### ISSUE THREAD

**Issue by jkeifer** [saz/puppet-sudo#263]
Puppet has released a new stdlib module at version 7.0.0. It looks like the dependency pinning of this module began being capped at version 4.2.0, and the current saz-sudo release 6.0.0 requires stdlib <7.0.0. If any other modules pull in stdlib 7.0.0 then the most recent compatible version of saz-sudo is resolved to be 4.1.0.

This is a bit of a strange and unexpected failure mode. Any way to resolve this?

**Comment by zilchms** [comment]
The proper way to resolve this in my opinion is to get a new version of saz-sudo out that supports the use of stdlib 7.x
I created an issue for this and will try to get a pullrequest out today, too. Should get some testing done first however.

**Comment by saz** [comment]
I've just released v7.0.0
