### ISSUE TITLE
Release 6.0.1?

### ISSUE THREAD

**Issue by hammondr** [saz/puppet-sudo#266]
Good morning.  We love your module and use it extensively.  We've wanted to update to v6.0.0 but it contains the "double percent sign" issue resolved in https://github.com/saz/puppet-sudo/commit/bdefa6530f80ccf8fcb63588a75f507ff33339e3 from 2019.

Would you consider releasing 6.0.1 from master so we can get that fix into our baseline?  Thanks!

The changes in https://github.com/saz/puppet-sudo/compare/v6.0.0...master all look good.

Thanks again.

**Comment by saz** [comment]
I've just released v7.0.0
