### ISSUE TITLE
wheel_config defaulting to 'absent' is undesirable, change to 'password'

### ISSUE THREAD

**Issue by canihavethisone** [saz/puppet-sudo#276]
This is contrary to OOB default and risks breaking production environments by denying members of the wheel group sudo privileges.  I feel that 'password' should be the default and allow people to change to 'absent' if so desired

**Comment by saz** [comment]
As far as I can see, before adding a parameter for wheel_config, it was commented out.

To be honest, I'd rather break production environments, then defaulting to `password`, which might be giving more permissions than expected. If someone needs this set to `password`, then it's possible and documented.

**Comment by msalway** [comment]
Prior to 80a5be316f0606599ed7ac06c656a72b543d5ae3 the templates for rhel7 and rhel8 enabled the wheel group as per the RedHat default.

I've provided a PR #278 that restores this behavior and retains the default of wheel_config=absent for all other OS's
