### ISSUE TITLE
Not All Files in /etc/sudoers.d Getting Purged

### ISSUE THREAD

**Issue by bpadgett505** [saz/puppet-sudo#286]
Hello,

I have recently setup this module in my environment.

During my testing last week I found that not all of the files that are not under Puppet control in /etc/sudoers.d are being purged.

I messed around with it for a couple of hours trying to find any correlation to the file names but was unable to.

Is this a known issue or could I be missing a declaration in my code to make this work properly?

Thanks.

**Comment by kenyon** [comment]
Files under puppet control aren't supposed to be purged, since puppet is managing them. Only non-managed files should be purged.

**Comment by bpadgett505** [comment]
Yes, I'm seeing files not under Puppet control that are not being purged.  Some are being purged.  Some are not.

**Comment by kenyon** [comment]
You might be able to tell why if you run puppet with `--debug`.

**Comment by bpadgett505** [comment]
Hiya,

Here is an example.  The files with a puppet-bak are not under puppet control but they are being handled.

115_sierra_romeo_foxtrot is being ignored by puppet and is not defined in my code.

-r--r----- 1 root root  99 Oct  7 12:20 10001_est-sa
-r--r----- 1 root root 103 Oct  7 12:20 101_mdwadms
-r--r----- 1 root root 102 Oct  7 12:20 102_asuite
-rw-r--r-- 1 root root   0 Oct  7 12:24 103_trout_fishing_rules.puppet-bak
-rw-r--r-- 1 root root   0 Oct  7 12:22 104_windows_sucks.puppet-bak
-rw-r--r-- 1 root root   0 Oct  7 12:27 115_sierra_romeo_foxtrot
-r--r----- 1 root root 104 Oct  7 12:20 11_bpadgett

I found at least three or four names last Friday that were being ignored.

Thanks for taking a look at my issue.

Here is a puppet debug run where I grep -i for sudo:

Debug: Facter: fact "sudoversion" has resolved to: 1.8.29
Debug: /Package[sudo]: Provider dnf does not support features targetable; not managing attribute command
Debug: /Stage[main]/Sudo::Package/before: before to File[/etc/sudoers]
Debug: /Stage[main]/Sudo::Package/before: before to File[/etc/sudoers.d]
Debug: /Stage[main]/Sudo/Sudo::Conf[mdwadms]/File[101_mdwadms]/require: require to File[/etc/sudoers.d]
Debug: /Stage[main]/Sudo/Sudo::Conf[mdwadms]/File[101_mdwadms]/notify: notify to Exec[sudo-syntax-check for file /etc/sudoers.d/101_mdwadms]
Debug: /Stage[main]/Sudo/Sudo::Conf[asuite]/File[102_asuite]/require: require to File[/etc/sudoers.d]
Debug: /Stage[main]/Sudo/Sudo::Conf[asuite]/File[102_asuite]/notify: notify to Exec[sudo-syntax-check for file /etc/sudoers.d/102_asuite]
Debug: /Stage[main]/Sudo/Sudo::Conf[est-sa]/File[10001_est-sa]/require: require to File[/etc/sudoers.d]
Debug: /Stage[main]/Sudo/Sudo::Conf[est-sa]/File[10001_est-sa]/notify: notify to Exec[sudo-syntax-check for file /etc/sudoers.d/10001_est-sa]
Debug: /Stage[main]/Sudo/Sudo::Conf[bpadgett]/File[11_bpadgett]/require: require to File[/etc/sudoers.d]
Debug: /Stage[main]/Sudo/Sudo::Conf[bpadgett]/File[11_bpadgett]/notify: notify to Exec[sudo-syntax-check for file /etc/sudoers.d/11_bpadgett]
Debug: /Stage[main]/Sudo/File[/etc/sudoers]: Adding autorequire relationship with User[root]
Debug: /Stage[main]/Sudo/File[/etc/sudoers]: Adding autorequire relationship with Group[root]
Debug: /Stage[main]/Sudo/File[/etc/sudoers.d]: Adding autorequire relationship with User[root]
Debug: /Stage[main]/Sudo/File[/etc/sudoers.d]: Adding autorequire relationship with Group[root]
Debug: /Stage[main]/Sudo/Sudo::Conf[mdwadms]/File[101_mdwadms]: Adding autorequire relationship with User[root]
Debug: /Stage[main]/Sudo/Sudo::Conf[mdwadms]/File[101_mdwadms]: Adding autorequire relationship with Group[root]
Debug: /Stage[main]/Sudo/Sudo::Conf[asuite]/File[102_asuite]: Adding autorequire relationship with User[root]
Debug: /Stage[main]/Sudo/Sudo::Conf[asuite]/File[102_asuite]: Adding autorequire relationship with Group[root]
Debug: /Stage[main]/Sudo/Sudo::Conf[est-sa]/File[10001_est-sa]: Adding autorequire relationship with User[root]
Debug: /Stage[main]/Sudo/Sudo::Conf[est-sa]/File[10001_est-sa]: Adding autorequire relationship with Group[root]
Debug: /Stage[main]/Sudo/Sudo::Conf[bpadgett]/File[11_bpadgett]: Adding autorequire relationship with User[root]
Debug: /Stage[main]/Sudo/Sudo::Conf[bpadgett]/File[11_bpadgett]: Adding autorequire relationship with Group[root]
Debug: /Stage[main]/Sudo/Sudo::Conf[mdwadms]/Exec[sudo-syntax-check for file /etc/sudoers.d/101_mdwadms]: 'visudo -c || ( rm -f '/etc/sudoers.d/101_mdwadms' && exit 1)' won't be executed because of failed check 'refreshonly'
Debug: /Stage[main]/Sudo/Sudo::Conf[asuite]/Exec[sudo-syntax-check for file /etc/sudoers.d/102_asuite]: 'visudo -c || ( rm -f '/etc/sudoers.d/102_asuite' && exit 1)' won't be executed because of failed check 'refreshonly'
Debug: /Stage[main]/Sudo/Sudo::Conf[est-sa]/Exec[sudo-syntax-check for file /etc/sudoers.d/10001_est-sa]: 'visudo -c || ( rm -f '/etc/sudoers.d/10001_est-sa' && exit 1)' won't be executed because of failed check 'refreshonly'
Debug: /Stage[main]/Sudo/Sudo::Conf[bpadgett]/Exec[sudo-syntax-check for file /etc/sudoers.d/11_bpadgett]: 'visudo -c || ( rm -f '/etc/sudoers.d/11_bpadgett' && exit 1)' won't be executed because of failed check 'refreshonly'

**Comment by kenyon** [comment]
I think it's probably failing because of bad permissions. Should be `0600` or `0660`, otherwise the `visudo -c` fails.

**Comment by saz** [comment]
Are you sure, those files are not managed by puppet? It might be possible, that there's neither sudo nor a part of the file name in the title, which won't therefore be matched by grep.

What happens if you're manually removing such a file and run puppet right after?

Which parameters are you setting?

**Comment by zilchms** [comment]
@bpadgett505 If you could also provide what your are feeding into your puppetcode, whether that be the relevant hiera entries or .pp files. That would be awesome. Would help immensely with debugging.

**Comment by saz** [comment]
`purge => true` must be set on the file resource `/etc/sudoers.d` to remove any unmanaged files. As this is some behavior of the puppet file type, it's not related to permissions (as new files are created and owned by `root`) or any validation command (this will only affect new or changed files).

Either those files are managed by puppet or `purge_ignore` is set and those files are matching and are therefore not removed (not sure if they will show up during an agent run with `--debug`).

Another idea: maybe something else is creating those files between agent runs?

**Comment by saz** [comment]
@bpadgett505 As there's no response for a longer time and nobody else reports this behavior, I'll close the issue. If you think it's still a valid issue, please let me know.
