### ISSUE TITLE
secure_path in params.pp set to incorrect defaults for recent Redhat releases

### ISSUE THREAD

**Issue by drakpzone** [saz/puppet-sudo#298]
$secure_path is set correctly for EL7 ad below, but default to excluding /usr/local/bin for el8 and default (including el9):

        /^7/: {
          $content_template = "${content_base}sudoers.rhel7.erb"
          $secure_path      = '/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin'
          $wheel_config     = 'password'
        }
        /^8/: {
          $content_template = "${content_base}sudoers.rhel8.erb"
          $secure_path      = '/sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin'
          $wheel_config     = 'password'
        }
        default: {
          $content_template = "${content_base}sudoers.rhel8.erb"
          $secure_path      = '/sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin'
          $wheel_config     = 'password'

**Comment by saz** [comment]
Looking at CentOS 9, the path seems correct:

```
Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin
```

There's also a parameter to set a different value for `secure_path`. I'd prefer sticking to the current value, as it's closer to the default value. Feel free to open this issue again to further discuss this topic.
