### ISSUE TITLE
Version 8 on the forge does include the RHEL9 template

### ISSUE THREAD

**Issue by arthurbarton** [saz/puppet-sudo#310]
See also https://github.com/saz/puppet-sudo/issues/287 & perhaps https://github.com/saz/puppet-sudo/issues/308

Fetching version 8.0.0 from the Forge does not include the RHEL 9 template, though it does include RHEL 9 as supported in the metadata.

Version 8.0.0 either in git tag or the Forge also doesn't include the **types** directory required for the sudo::defaults types. Though this is only mentioned in README/REFERENCE for the master branch not v8

**Comment by saz** [comment]
Should be fixed with v9 I've published today.
