### ISSUE TITLE
sudo-syntax-check error in puppet-sudo version 3.0.5

### ISSUE THREAD

**Issue by flakrat** [saz/puppet-sudo#60]
Howdy, I'm getting the following when attempting to apply the catalog to a node:

```
Info: Applying configuration version '1397793067'
Error: Could not apply complete catalog: Found 1 dependency cycle:
(Exec[sudo-syntax-check for file /etc/sudoers.d/5_sysadmins] => File[5_sysadmins] => Exec[sudo-syntax-check for file /etc/sudoers.d/5_sysadmins])
Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
Notice: Finished catalog run in 0.32 seconds
```

If I comment out the following line, the /etc/sudoers.d/5_sysadmins file gets created and manually running "visudo -c " shows that it checks out OK. I'm also able to successfully run the sudo command for my user who is part of the wheel group.

```
    require => Exec["sudo-syntax-check for file ${cur_file}"],
```

The following is how I'm configuring the node in hiera

```
sudo::conf:
  sysadmins:
    priority: 5
    content: "%wheel ALL=(ALL) ALL"
```

**Comment by hnnsngl** [comment]
As of now, the file resource does have a validate_cmd attribute, that lends itself to this:
...
validate_cmd => '/usr/sbin/visudo --check --file=%',
...
